// © Creative Services and Development
// Site Oficial: www.creativesd.com.br
// Termos de Contrato e Autoria em: http://creativesd.com.br/?p=termos

/*==========================================
 * CreativeSD: Ranked System
 *------------------------------------------*/
void clif_ranked_belonginfo(struct map_session_data *sd, struct guild *g);
void clif_remove_belonginfo(struct map_session_data *sd);
void clif_visual_emblem(struct map_session_data *sd, struct guild *g);